### ISSUE TITLE
Sigularity image?

### ISSUE THREAD

**Issue by KeyTals** [ccmbioinfo/MetaFusion#1]
Hello,

Is it possible to provide singularity command for this as docker is not allowed in some HPCs environment but singularity is allowed.

Thanks,
Keyur

**Comment by mapostolides** [comment]
Hi Keyur,

I am currently working on a singularity implementation, will update the wiki when I have the documentation finished. In the meantime, it is still possible to install MetaFusion with the correct dependencies as outlined here: https://github.com/ccmbioinfo/MetaFusion/wiki/Installation-without-Docker

Thanks!
Michael

**Comment by mapostolides** [comment]
Hi Keyur,

I've created a Singularity container. Instructions for running it on an HPC cluster can be found here.
https://github.com/ccmbioinfo/MetaFusion/wiki/Singularity

Thanks!
