### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mobiusklein** [ccmbioinfo/MetaFusion#3]
I'm looking at evaluating this pipeline for comparison with other fusion calling ensembles, but didn't see a license on the repository. Is it licensed under any of the standard OSS licenses and/or are there any restrictions?

**Comment by mike8115** [comment]
Hi Joshua, thanks for asking and bringing this to our attention! I've added the license for LGPL3.0 to the repository.

**Comment by mobiusklein** [comment]
Thank you, that clarifies things.
