### ISSUE TITLE
What is Metafusion.clinical?

### ISSUE THREAD

**Issue by pintoa1-mskcc** [ccmbioinfo/MetaFusion#5]
We are hoping to utilize metafusion for our pipeline. We are interested in what the Wiki calls Metafusion.clinical, but there isnt any information on how to run, generate or the difference in this pipeline vs regular Metafusion. 

Is Metafusion.clinical a different pipeline? How do we generate the results

**Comment by mike8115** [comment]
Hi there,

Thank you for your interest. Yes, Metafusion.clinical is an upgraded version of the currently available MetaFusion pipeline. Our paper describing Metafusion.clinical is currently in reviews. We are planning to make this new pipeline and its documentation available upon the publication. 

Regarding other information, the wiki on this repository will largely apply to Metafusion.clinical once it is ready for release.

Hope that helps!

**Comment by pintoa1-mskcc** [comment]
Thanks! I'll be looking out for the update! Do you have any estimate to when the release will be?

**Comment by mike8115** [comment]
Unfortunately, I don't have an ETA. I'm aware that the authors are currently going through the manuscript is going through the review process, but I haven't received futher updates.
