### ISSUE TITLE
Out-of-frame/utr5 breakpoints results in "CodingFusion" call

### ISSUE THREAD

**Issue by pintoa1-mskcc** [ccmbioinfo/MetaFusion#7]
Hi! 

I have a Fusion  RAB21-WNK1, which is called by three fusion callers: fusionCatcher, arriba and star-fusion with frame information out-of-frame -- out-of-frame, CDS/splicesite -- CDS/splicesite and FRAMESHIFT -- FRAMESHIFT, respectively. The breakpoints are  chr12:72176438 -- chr12:922808 for all callers.

Upon renaming and reannotation, metafusion now calls the frames utr5--cds. The category the metafusion calls is CodingFusion. 

Our institute is very interested in frame information, and we had assumed from the paper that a utr5--cds fusion wouldn't be called a CodingFusion. This call is concerning to us, would you all be able to provide further information on why a supposedly out-of-frame fusion is being called a CodingFusion?

Edit: we think this would be a TruncatedCoding call, however after reviewing the paper we do agree with the CodingFusion call assuming the reason this a codingFusion is because RAB21 is NOT a pseudogene, even though a "utr5" region is "noncoding?"

**Comment by mapostolides** [comment]
Hi @pintoa1-mskcc , thanks for your question about this. 

I agree with your conclusion in the edit to your initial comment. The categories that MetaFusion uses are about the types of genes between which the fusion occurs. The question of whether the fusion will produce a coding product is indeed a separate question, which can be determined by frame information provided by the callers.

**Comment by pintoa1-mskcc** [comment]
Thank you!
