### ISSUE TITLE
WITH_SEQ CFF file is_inframe Column

### ISSUE THREAD

**Issue by pintoa1-mskcc** [ccmbioinfo/MetaFusion#8]
Hi,

I have been digging through the code to understand the intermediates, and one column "is_inframe" seems to always be set as False in all my samples, meaning that none of my fusions are in-frame. However AGFusion will reannotate and will sometimes change this to an in frame fusion. I know this column isn't mentioned anywhere in the Wiki, but I was wondering if it was significant for analysis or clustering at all?

**Comment by mapostolides** [comment]
Only the gene names and breakpoints are used for the clustering. There are a number of intermediate fields, some of which might have been features we had intended to add, or which were later added in the second iteration of this tool. In this case, the column "is_inframe" has no meaning for your analysis. Hope this helps!
