### ISSUE TITLE
Metafusion and references

### ISSUE THREAD

**Issue by pintoa1-mskcc** [ccmbioinfo/MetaFusion#9]
Hi,

I see that we can provide a genome_fasta to metafusion, but gene_bed seems to be specific to metafusion. Is there a way to generate gene_bed without relying on metafusions annotation? We are having an issue matching ensembl names with a secondardy tool and would like to be able to change the references as we see fit. 

If we cannot change references, we will not be able to use this tool.

**Comment by mike8115** [comment]
Had to dig into the source code for a while, but looks like `gene_bed` is a whitespace delimited file without any headers or comments. Each row should contain the following (with the exact order):

1. Chromosome
2. Start position - 0-based positioning, inclusive
3. End position - 0-based, exclusive
4. Transcript ID
5. Feature type - One of utr, intron, cds
6. idx - Integer; not documented. My best guess is that this is the discriminator for each transcript ID and feature pairing. The examples always seems to start at 0.
7. Strand - Use either f to indicate forward or r to indicate reverse strand
8. Gene Name
9. Gene ID

You could probably create this file by parsing and transforming data from Ensembl's GFF/GTF files through reverse engineering. 

@mapostolides, do you happen to have instructions about this?

**Comment by mike8115** [comment]
I found some notes @mapostolides left behind in his old work directories. The attached archive should have an R markdown and text file outlining his steps.

[original_make_annot_script.zip](https://github.com/ccmbioinfo/MetaFusion/files/11580517/original_make_annot_script.zip)

**Comment by pintoa1-mskcc** [comment]
Thanks! I will work to reproduce

**Comment by pintoa1-mskcc** [comment]
I managed to get a reference create for my specific version of ensembl gtf. It does seem that for any new references, there will be some level of manual review needed as different versions of gtfs have different values.
